---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master

notifications:
  email:
    recipients:
      - bradley.soper@dell.com
      - craig.j.smith@dell.com
    on_success: always # default: change
    on_failure: always # default: always

notifications:
  slack: underground-collab:TOL2vnKU35RPWigEw0Ivfw8V
